//"use client";
import { Controll } from "./Controll";
import "./globals.css";
import Link from "next/link";

export const metadata = {
<<<<<<< HEAD
  title: "Web tutorials",
  description: "Generated by jw",
};
=======
  title : "Web tutorial",
  description: "Generated by Jw"
}
>>>>>>> 414a0736745d95aa177055979bd2324d53b72b78

export default async function RootLayout({ children }) {
    const response = await fetch('https://pretty-flannel-spirit.glitch.me/'+"topics",{cache:"no-store"});
    // const response = await fetch("http://localhost:9999/topics",{next:{revalidate:0}});
    const topics = await response.json();
    console.log(topics)
  return (
    <html>
      <body>
        <h1>
<<<<<<< HEAD
          <a href="/">WEB</a>
        </h1>
        <ol>
          <li>
            <a href="/read/1">html</a>
          </li>
          <li>
            <a href="/read/2">css</a>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <a href="/create">Create</a>
          </li>
          <li>
            <a href="/update/1">Update</a>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
=======
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Controll />
>>>>>>> 414a0736745d95aa177055979bd2324d53b72b78
      </body>
    </html>
  );
}
