//"use client";
import { Controll } from "./Controll";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title : "Web tutorial",
  description: "Generated by Jw"
}

export default async function RootLayout({ children }) {
    const response = await fetch(process.env.NEXT_PUBLIC_API_URL+"topics",{cache:"no-store"});
    // const response = await fetch("http://localhost:9999/topics",{next:{revalidate:0}});
    const topics = await response.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Controll />
      </body>
    </html>
  );
}
